### ISSUE TITLE
Readme.md .env template invalid token name

### ISSUE THREAD

**Issue by ScienceyZac** [aria-development/Shunka#21]
in the readme.md the .env file template has a invalid token name, the mongo uri is suppost to be: `MONGO_URI`
but instead it is: `MOnGO_URI`

**Comment by kakarot-dev** [comment]
really sorry zac, Will get it fixed

**Comment by kakarot-dev** [comment]
Done, also there are some pushes going to be pushed to remove some typescript errors, Watch out for that 😄
